CONFIG_NAME: interop
PRESET_BASE: interop

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Time parameters
SECONDS_PER_SLOT: 5
SLOTS_PER_EPOCH: 6
ETH1_FOLLOW_DISTANCE: 8
EPOCHS_PER_ETH1_VOTING_PERIOD: 2

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242